matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.md'
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - en-custom.txt
    output: build/dictionary/python.dic
  default_encoding: utf-8
