matrix:
- name: markdown
  pipeline:
    - pyspelling.filters.markdown:
        markdown_extensions:
        - pymdownx.superfences:
        - pymdownx.highlight:
  sources:
  - '**/*.md'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - en-custom.txt
    output: build/dictionary/python.dic
  default_encoding: utf-8
